// <auto-generated />
using System;
using CardapioSnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CardapioSnd.Migrations
{
    [DbContext(typeof(BancoContext))]
    partial class BancoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardapioSnd.Models.AlimentoModel", b =>
            {
                b.Property<int>("ID_ALIMENTO")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_ALIMENTO"));

                b.Property<string>("DS_ALIMENTO")
                    .IsRequired()
                    .HasColumnType("VARCHAR(150)");

                b.Property<string>("TP_ALIMENT0")
                    .IsRequired()
                    .HasColumnType("VARCHAR(50)");

                b.HasKey("ID_ALIMENTO");

                b.ToTable("ALIMENTO_SIS_CARDAPIO");
            });

            modelBuilder.Entity("CardapioSnd.Models.CardapioModel", b =>
            {
                b.Property<int>("ID_CARDAPIO")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CARDAPIO"));

                b.Property<string>("CARNE")
                    .IsRequired()
                    .HasColumnType("VARCHAR(150)");

                b.Property<string>("DATA_CARDAPIO")
                    .IsRequired()
                    .HasColumnType("VARCHAR(25)");

                b.Property<string>("EXTRAS")
                    .HasColumnType("VARCHAR(150)");

                b.Property<string>("GUARNICAO")
                    .IsRequired()
                    .HasColumnType("VARCHAR(150)");

                b.Property<string>("SALADA_LEGUMES")
                    .IsRequired()
                    .HasColumnType("VARCHAR(150)");

                b.HasKey("ID_CARDAPIO");

                b.ToTable("CARDAPIO_SIS_CARDAPIO");
            });

            modelBuilder.Entity("CardapioSnd.Models.UsuarioModel", b =>
            {
                b.Property<int>("ID_USUARIO")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USUARIO"));

                b.Property<DateTime?>("DATA_ATUALIZACAO")
                    .HasColumnType("DATE");

                b.Property<DateTime>("DATA_CADASTRO")
                    .HasColumnType("DATE");

                b.Property<string>("EMAIL")
                    .IsRequired()
                    .HasColumnType("VARCHAR(150)");

                b.Property<string>("LOGIN")
                    .IsRequired()
                    .HasColumnType("VARCHAR(20)");

                b.Property<string>("NOME")
                    .IsRequired()
                    .HasColumnType("VARCHAR(2000)");

                b.Property<int>("PERFIL")
                    .HasColumnType("NUMBER(10)");

                b.Property<string>("SENHA")
                    .IsRequired()
                    .HasColumnType("VARCHAR(10)");

                b.HasKey("ID_USUARIO");

                b.ToTable("USUARIO_SIS_CARDAPIO");
            });
#pragma warning restore 612, 618
        }
    }
}
